### ISSUE TITLE
UpToDateStubIndexMismatch: PSI and index do not match.

### ISSUE THREAD

**Issue by mesour** [nette-intellij/intellij-neon#58]
Version: 1.0.0-alfa2

```
com.intellij.psi.stubs.UpToDateStubIndexMismatch: PSI and index do not match.
Please report the problem to JetBrains with the files attached
INDEXED VERSION IS THE CURRENT ONE file=NeonFile:scheduler.neon, file.class=class cz.juzna.intellij.neon.psi.impl.NeonFileImpl, file.lang=Language: neon, modStamp=3
 tree consistent
 stub debugInfo=created in getStubTree(), with AST = false; with backReference
latestIndexedStub=StubTree{myDebugInfo='created from index; with backReference', myRoot=PsiFileStubImpl}1142855069
   same size=true
   debugInfo=created from index; with backReference
 viewProvider=cz.juzna.intellij.neon.file.NeonFileViewProvider{vFile=file:///private/var/www/public_html/feedtrack/backend/config/app/scheduler.neon, vFileId=5369, content=VirtualFileContent{size=4934}, eventSystemEnabled=true}
 viewProvider stamp: 1719247; file stamp: 1719247; file modCount: 1615338579741; file length: 4934
 doc saved: true; doc stamp: 1719247; doc size: 4934; committed: true
indexing info: indexing timestamp = 1615338579741, binary = false, byte size = 4934, char size = 4934
	at com.intellij.psi.stubs.StubTreeLoader.handleUpToDateMismatch(StubTreeLoader.java:135)
	at com.intellij.psi.stubs.StubTreeLoader.stubTreeAndIndexDoNotMatch(StubTreeLoader.java:128)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:201)
	at com.intellij.psi.impl.source.FileTrees.withAst(FileTrees.java:149)
	at com.intellij.psi.impl.source.PsiFileImpl.loadTreeElement(PsiFileImpl.java:216)
	at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:734)
	at com.intellij.psi.impl.source.PsiFileImpl.getChildren(PsiFileImpl.java:739)
	at cz.juzna.intellij.neon.util.NeonPsiUtil.acceptAllFiles(NeonPsiUtil.java:38)
	at cz.juzna.intellij.neon.util.NeonPsiUtil.acceptAllFiles(NeonPsiUtil.java:19)
	at cz.juzna.intellij.neon.util.NeonPhpUtil.attachNeonParameterUsages(NeonPhpUtil.java:328)
	at cz.juzna.intellij.neon.inspections.NeonUnusedKeyInspection$1.visitElement(NeonUnusedKeyInspection.java:64)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at cz.juzna.intellij.neon.psi.impl.NeonKeyValPairImpl.accept(NeonKeyValPairImpl.java:27)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:67)
	at com.intellij.psi.PsiWalkingState.visit(PsiWalkingState.java:24)
	at com.intellij.util.WalkingState.walkChildren(WalkingState.java:62)
	at com.intellij.util.WalkingState.elementStarted(WalkingState.java:49)
	at com.intellij.psi.PsiWalkingState.elementStarted(PsiWalkingState.java:76)
	at com.intellij.psi.PsiRecursiveElementWalkingVisitor.visitElement(PsiRecursiveElementWalkingVisitor.java:48)
	at cz.juzna.intellij.neon.inspections.NeonUnusedKeyInspection$1.visitElement(NeonUnusedKeyInspection.java:83)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:273)
	at cz.juzna.intellij.neon.psi.impl.NeonMainArrayImpl.accept(NeonMainArrayImpl.java:28)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:185)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:754)
	at cz.juzna.intellij.neon.inspections.NeonUnusedKeyInspection.checkFile(NeonUnusedKeyInspection.java:34)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:145)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:66)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$6(LocalInspectionsPass.java:321)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:321)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.AssertionError: Stub count doesn't match stubbed node length
	at com.intellij.psi.impl.source.FileTrees.lambda$reconcilePsi$5(FileTrees.java:189)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:577)
	at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:182)
	... 49 more
```

**Comment by mesour** [comment]
Experimental version is closed and replaced with new https://plugins.jetbrains.com/plugin/18387-neon-nette-support plugin
